remote_theme : "mmistakes/minimal-mistakes@4.24.0"
url                      : "https://jason-lee-91.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
