#remote_theme: just-the-docs/just-the-docs
theme: "just-the-docs"

minimal_mistakes_skin    : "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
future                   : true
# Site Settings
locale                   : "ko-KR"
title                    : "기술 블로그"
title_separator          : "-"
subtitle                 : "기술 블로그"# site tagline that appears below site title in masthead
name                     : "Jason"
description              : "기술 블로그"
url                      : "jason-lee-91.github.io"# the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : ""# the subpath of your site, e.g. "/blog"
repository               : # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
gh_edit_repository: "https://github.com/jason-lee-91/jason-lee-91.github.io/" # the github URL for your repo